;; This Clojure file contains miscellaneous data generated by the qftp project
;; It's mostly used as an archive of useful "research" data

(def socket-server-return
  "The return from invoking (async-sockets/socket-server 22)
  This is a record AsyncSocketServer that wraps an initialized Java ServerSocket object"
  {:#com.gearswithingears.async_sockets.AsyncSocketServer
      {:port 22,
       :backlog 50,
       :bind-addr nil,
       :server "#object[java.net.ServerSocket 0x14f7d7 ServerSocket[addr=0.0.0.0/0.0.0.0,localport=22]]",
       :connections "#object[clojore.async.impl.channels.ManyToManyChannel 0x596c4c clojure.core.async.impl.channels.ManyToManyChannel@596c4c]"}})

(def connection
  "A connection from a inside the server.
  Copied off the socket-server's :connections channel."
  {:#com.gearswithingears.async_sockets.AsyncSocket
   {:socket "#object[java.net.Socket 0x122d0a9 Socket[addr=/127.0.0.1,port=53867,localport=22]]",
    :address "#object[java.net.InetSocketAddress 0x1919fdc 0.0.0.0/0.0.0.0:22]",
    :in-ch nil,
    :out-ch nil,
    :in "#object[clojure.core.async.impl.channels.ManyToManyChannel 0x1e53b3d clojure.core.async.impl.channels.ManyToManyChannel@1e53b3d]",
    :out "#object[clojure.core.async.impl.channels.ManyToManyChannel 0x1dabbd9 clojure.core.async.impl.channels.ManyToManyChannel@1dabbd9]"}})

(def filezilla-connect
  "This is the first line of the connection sequence for FileZilla over localhost FTP port 22"
  "ECHO:  SSH-2.0-PuTTY_Local:_Mar__2_2015_21:30:06")


(def lan-client-connection
  "A connection from a inside the server.
  Copied off the socket-server's :connections channel."
  {:user "quest", :pass nil,
   :control-connection {"#com.gearswithingears.async_sockets.AsyncSocket{:socket #object[java.net.Socket 0xfed1d Socket[addr=/192.168.1.41,port=46317,localport=21]]",
                        :address "#object[java.net.InetSocketAddress 0x9ba03d 0.0.0.0/0.0.0.0:21]",
                        :in-ch nil, :out-ch nil,
                        :in "#object[clojure.core.async.impl.channels.ManyToManyChannel 0x10d6ef8 clojure.core.async.impl.channels.ManyToManyChannel@10d6ef8]",
                        :out "#object[clojure.core.async.impl.channels.ManyToManyChannel 0x193415a clojure.core.async.impl.channels.ManyToManyChannel@193415a]"},
   :data-connection {:active? false, :server-port 20, :client-port nil, :socket nil},
   :fsm-state {:accepted? false, :checkpoint nil, :state-index 2, :start-index 0, :stream-index 2, :value nil}, :working-directory "/", :processing? true})

; A "session" object containing an async connection and an fsm-atom
{:user nil, :pass nil,
 :connection "#com.gearswithingears.async_sockets.AsyncSocket"
 {:socket #object[java.net.Socket 0xc96c99 Socket[addr=/127.0.0.1,port=58246 .InetSocketAddress 0x28641a 0.0.0.0/0.0.0.0:22],
                  :in-ch nil, :out-ch nil,
                  :in #object[clojure.core.async.impl.channels.ManyToManyChannel 0xe9730 clojure.core.async.impl.channels.ManyToManyChannel@e9730],
                  :out #object[clojure.core.async.impl.channels.ManyToManyChannel 0x3107e9 clojure.core.async.impl.channels.ManyToManyChannel@3107e9]},
 :fsm-state #object[clojure.lang.Atom 0x1a7cbda {:status :ready, :val #object[pure_ftp.fsm$construct 0xaa4cbf pure_ftp.fsm$construct@aa4cbf]}]}

; I setup a SocketTest server to where the data port should've been and did a LIST
; QFTP sent the below input. 2016/05/13

;> Server Started on Port: 1039
;> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;    > New Client: 127.0.0.1
;example.txt test10 test3 test4 test5 test6
;> Client closed conection.

(def received-list-retr
  "This was sent to a test Socket program that was the DATA destination.
  The control connection requested a directory listing and then a text file
  that had the contents 'simple'"
  "> Client closed conection.
  > New Client: 127.0.0.1
  drwxr-xr-x 1 ftp ftp              0 Apr 10 19:55 Camera Roll
  -rw-r--r-- 1 ftp ftp            504 Apr 12 19:22 desktop.ini
  -rw-r--r-- 1 ftp ftp              6 May 13 23:26 simple.txt
  drwxr-xr-x 1 ftp ftp              0 Mar 26  2016 VideoWebDownloader
  drwxr-xr-x 1 ftp ftp              0 May 12 18:19 Warframe
  > Client closed conection.
  > New Client: 127.0.0.1
  simple> Client closed conection.")


; This is FileZilla's "received-list-retr" server log
"(000004)5/13/2016 23:35:24 PM - quest (192.168.1.41)> 230 Logged on
(000004)5/13/2016 23:35:24 PM - quest (192.168.1.41)> SYST
(000004)5/13/2016 23:35:24 PM - quest (192.168.1.41)> 215 UNIX emulated by FileZilla
(000004)5/13/2016 23:35:31 PM - quest (192.168.1.41)> PORT 192,168,1,41,201,154
(000004)5/13/2016 23:35:31 PM - quest (192.168.1.41)> 200 Port command successful
(000004)5/13/2016 23:35:31 PM - quest (192.168.1.41)> LIST
(000004)5/13/2016 23:35:31 PM - quest (192.168.1.41)> 150 Opening data channel for directory listing of "/"
(000004)5/13/2016 23:35:31 PM - quest (192.168.1.41)> 226 Successfully transferred \/""
(000004)5/13/2016 23:35:39 PM - quest (192.168.1.41)> PORT 192,168,1,41,173,21
(000004)5/13/2016 23:35:39 PM - quest (192.168.1.41)> 200 Port command successful
(000004)5/13/2016 23:35:39 PM - quest (192.168.1.41)> RETR simple.txt
(000004)5/13/2016 23:35:39 PM - quest (192.168.1.41)> 150 Opening data channel for file download from server of \"simple.txt\"
(000004)5/13/2016 23:35:39 PM - quest (192.168.1.41)> 226 Successfully transferred \"simple.txt\""

